# Site settings
title: Fumitsuki's magic box
email: requiem.for.memories@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  這是文月放部落格文章的備份的地方。
  希望這個破破爛爛的百寶箱，你也能找到許多引起你興趣的小東西:)
baseurl: "/blog"
url: "http://requiemformemories.github.io" # the base hostname & protocol for your site
twitter_username: Fumitsuki0802
github_username:  requiemformemories

# Build settings
markdown: kramdown

paginate: 4

author: Fumitsuki 文月

gems: [jekyll-paginate]
